### ISSUE TITLE
[Tracking] Activity

### ISSUE THREAD

**Issue by yrashk** [bpxe/bpxe#15]
- [ ] Better error handling / reporting
- [ ] Ensure all data association sources and destinations are supported
- [ ] Figure out deterministic state recovery for standard loops and multi-instance loops
- [ ] [`*DataAssociation::transformation`](https://docs.bpxe.rs/master/bpxe_bpmn_schema/trait.DataAssociationType.html#tymethod.transformation) handling
- [ ] [`*DataAssociation::assignments`](https://docs.bpxe.rs/master/bpxe_bpmn_schema/trait.DataAssociationType.html#tymethod.assignments) handling
- [ ] [`default` attribute](https://docs.bpxe.rs/master/bpxe_bpmn_schema/trait.ActivityType.html#tymethod.default) handling
- [ ] [`MultiInstanceLoopCharacteristics::behavior`](https://docs.bpxe.rs/master/bpxe_bpmn_schema/trait.MultiInstanceLoopCharacteristicsType.html#tymethod.behavior) handling (event throwing)
- [ ] [`startQuantity` attribute](https://docs.bpxe.rs/master/bpxe_bpmn_schema/trait.ActivityType.html#tymethod.start_quantity) handling
- [ ] [`completionQuantity` attribute](https://docs.bpxe.rs/master/bpxe_bpmn_schema/trait.ActivityType.html#tymethod.completion_quantity) handling
